-- Base de datos: personal_db
-- Estructura de la tabla `personal` basada en las capturas de pantalla proporcionadas.

CREATE TABLE `personal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Grado` VARCHAR(50) DEFAULT NULL,
  `Nombres` VARCHAR(100) NOT NULL,
  `Paterno` VARCHAR(50) NOT NULL,
  `Materno` VARCHAR(50) DEFAULT NULL,
  `NrRut` VARCHAR(20) NOT NULL,
  `fechaNacimiento` date DEFAULT NULL,
  `sexo` VARCHAR(10) DEFAULT NULL,
  `estadoCivil` VARCHAR(50) DEFAULT NULL,
  `nrEmpleado` VARCHAR(50) DEFAULT NULL,
  `puesto` VARCHAR(100) DEFAULT NULL,
  `especialidadPrimaria` VARCHAR(100) DEFAULT NULL,
  `fechaIngreso`date DEFAULT NULL,
  `fechaPresentacion` date DEFAULT NULL, 
  `Unidad` VARCHAR(100) DEFAULT NULL,
  `unidadEspecifica` VARCHAR(100) DEFAULT NULL,
  `categoria` VARCHAR(50) DEFAULT NULL,
  `escalafon` VARCHAR(50) DEFAULT NULL,
  `trabajoExterno` VARCHAR(100) DEFAULT NULL,
  `calle` VARCHAR(255) DEFAULT NULL,
  `numeroDepto` VARCHAR(50) DEFAULT NULL,
  `poblacionVilla` VARCHAR(100) DEFAULT NULL,
  `telefonoFijo` VARCHAR(50) DEFAULT NULL,
  `movil1` VARCHAR(50) DEFAULT NULL,
  `movil2` VARCHAR(50) DEFAULT NULL,
  `email1` VARCHAR(100) DEFAULT NULL,
  `email2` VARCHAR(100) DEFAULT NULL,
  `anexo` VARCHAR(50) DEFAULT NULL,
  `foto` VARCHAR(255) DEFAULT NULL,
  `prevision` VARCHAR(100) DEFAULT NULL,
  `sistemaSalud` VARCHAR(100) DEFAULT NULL,
  `regimenMatrimonial` VARCHAR(50) DEFAULT NULL,
  `religion` VARCHAR(100) DEFAULT NULL,
  `tipoVivienda` VARCHAR(100) DEFAULT NULL,
  `nombreConyuge` VARCHAR(200) DEFAULT NULL,
  `profesionConyuge` VARCHAR(100) DEFAULT NULL,
  `nombreContactoEmergencia` VARCHAR(200) DEFAULT NULL,
  `direccionEmergencia` VARCHAR(255) DEFAULT NULL,
  `movilEmergencia` VARCHAR(50) DEFAULT NULL,
  `Estado` tinyint(1) DEFAULT NULL,
  `fechaExpiracion` DATE DEFAULT NULL,
  `accesoPermanente` tinyint(1) DEFAULT NULL,
  `es_residente` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `NrRut_UNIQUE` (`NrRut`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;